version: "3.8"

services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./face_db.sqlite3:/app/face_db.sqlite3
    restart: unless-stopped
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
