"""create user_embeddings table

Revision ID: 4ddd4729f1a8
Revises: 
Create Date: 2025-07-15 16:55:48.438962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ddd4729f1a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding_pc', sa.JSON(), nullable=True),
    sa.Column('embedding_mb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_embeddings_id'), 'user_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_user_embeddings_user_id'), 'user_embeddings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_embeddings_user_id'), table_name='user_embeddings')
    op.drop_index(op.f('ix_user_embeddings_id'), table_name='user_embeddings')
    op.drop_table('user_embeddings')
    # ### end Alembic commands ###
