require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KpiItemsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # KpiItem. As you add validations to KpiItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KpiItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all kpi_items as @kpi_items" do
      kpi_item = KpiItem.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:kpi_items)).to eq([kpi_item])
    end
  end

  describe "GET #show" do
    it "assigns the requested kpi_item as @kpi_item" do
      kpi_item = KpiItem.create! valid_attributes
      get :show, params: {id: kpi_item.to_param}, session: valid_session
      expect(assigns(:kpi_item)).to eq(kpi_item)
    end
  end

  describe "GET #new" do
    it "assigns a new kpi_item as @kpi_item" do
      get :new, params: {}, session: valid_session
      expect(assigns(:kpi_item)).to be_a_new(KpiItem)
    end
  end

  describe "GET #edit" do
    it "assigns the requested kpi_item as @kpi_item" do
      kpi_item = KpiItem.create! valid_attributes
      get :edit, params: {id: kpi_item.to_param}, session: valid_session
      expect(assigns(:kpi_item)).to eq(kpi_item)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new KpiItem" do
        expect {
          post :create, params: {kpi_item: valid_attributes}, session: valid_session
        }.to change(KpiItem, :count).by(1)
      end

      it "assigns a newly created kpi_item as @kpi_item" do
        post :create, params: {kpi_item: valid_attributes}, session: valid_session
        expect(assigns(:kpi_item)).to be_a(KpiItem)
        expect(assigns(:kpi_item)).to be_persisted
      end

      it "redirects to the created kpi_item" do
        post :create, params: {kpi_item: valid_attributes}, session: valid_session
        expect(response).to redirect_to(KpiItem.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved kpi_item as @kpi_item" do
        post :create, params: {kpi_item: invalid_attributes}, session: valid_session
        expect(assigns(:kpi_item)).to be_a_new(KpiItem)
      end

      it "re-renders the 'new' template" do
        post :create, params: {kpi_item: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kpi_item" do
        kpi_item = KpiItem.create! valid_attributes
        put :update, params: {id: kpi_item.to_param, kpi_item: new_attributes}, session: valid_session
        kpi_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested kpi_item as @kpi_item" do
        kpi_item = KpiItem.create! valid_attributes
        put :update, params: {id: kpi_item.to_param, kpi_item: valid_attributes}, session: valid_session
        expect(assigns(:kpi_item)).to eq(kpi_item)
      end

      it "redirects to the kpi_item" do
        kpi_item = KpiItem.create! valid_attributes
        put :update, params: {id: kpi_item.to_param, kpi_item: valid_attributes}, session: valid_session
        expect(response).to redirect_to(kpi_item)
      end
    end

    context "with invalid params" do
      it "assigns the kpi_item as @kpi_item" do
        kpi_item = KpiItem.create! valid_attributes
        put :update, params: {id: kpi_item.to_param, kpi_item: invalid_attributes}, session: valid_session
        expect(assigns(:kpi_item)).to eq(kpi_item)
      end

      it "re-renders the 'edit' template" do
        kpi_item = KpiItem.create! valid_attributes
        put :update, params: {id: kpi_item.to_param, kpi_item: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested kpi_item" do
      kpi_item = KpiItem.create! valid_attributes
      expect {
        delete :destroy, params: {id: kpi_item.to_param}, session: valid_session
      }.to change(KpiItem, :count).by(-1)
    end

    it "redirects to the kpi_items list" do
      kpi_item = KpiItem.create! valid_attributes
      delete :destroy, params: {id: kpi_item.to_param}, session: valid_session
      expect(response).to redirect_to(kpi_items_url)
    end
  end

end
